--liquibase formatted sql

-- products va product_images ID'lari UUID'dan ketma-ket raqamga (bigint identity) o'tadi.
-- Katalog baribir ochiq (GET /api/products permitAll) — yashiradigan narsa yo'q, raqamli
-- ID esa URL'da qulay va "42-kitob" deb gaplashiladi. Buyurtma/foydalanuvchi ID'lari
-- ataylab UUID bo'lib qoladi: ularni taxmin qilib bo'lmasligi kerak.
--
-- Mavjud qatorlar saqlanadi: har UUID'ga yangi raqam beriladi va bog'liq FK'lar
-- (product_images.product_id, order_items.product_id) o'sha xaritaga ko'ra yangilanadi.
-- Butun fayl bitta tranzaksiyada bo'lishi uchun barcha qadamlar bitta changeset'da —
-- yarim yo'lda xato bo'lsa hech nima o'zgarmagan holda qoladi.

--changeset kitobgo:0017-products-bigint-id
-- 1) Yangi ustunlar (vaqtincha, keyin asl nomiga o'tadi).
ALTER TABLE products       ADD COLUMN id_new         bigint;
ALTER TABLE product_images ADD COLUMN id_new         bigint;
ALTER TABLE product_images ADD COLUMN product_id_new bigint;
ALTER TABLE order_items    ADD COLUMN product_id_new bigint;

-- 2) Raqamlash. Tartib faqat deterministiklik uchun (yaratilish vaqti saqlanmagan):
--    kitoblar eski UUID bo'yicha, rasmlar esa kitob + sort_order bo'yicha.
WITH numbered AS (
    SELECT id, row_number() OVER (ORDER BY id) AS rn FROM products
)
UPDATE products p SET id_new = n.rn FROM numbered n WHERE p.id = n.id;

WITH numbered AS (
    SELECT id, row_number() OVER (ORDER BY product_id, sort_order, id) AS rn FROM product_images
)
UPDATE product_images i SET id_new = n.rn FROM numbered n WHERE i.id = n.id;

-- 3) FK qiymatlarini yangi raqamlarga ko'chirish.
UPDATE product_images i SET product_id_new = p.id_new FROM products p WHERE i.product_id = p.id;
UPDATE order_items    o SET product_id_new = p.id_new FROM products p WHERE o.product_id = p.id;

-- 4) Eski constraint va ustunlarni olib tashlab, yangilarini asl nomiga o'tkazish.
ALTER TABLE order_items    DROP CONSTRAINT order_items_product_fk;
ALTER TABLE product_images DROP CONSTRAINT product_images_product_fk;
ALTER TABLE product_images DROP CONSTRAINT product_images_pkey;
ALTER TABLE products       DROP CONSTRAINT products_pkey;

ALTER TABLE products DROP COLUMN id;
ALTER TABLE products RENAME COLUMN id_new TO id;
ALTER TABLE products ALTER COLUMN id SET NOT NULL;
ALTER TABLE products ADD CONSTRAINT products_pkey PRIMARY KEY (id);

ALTER TABLE product_images DROP COLUMN id;
ALTER TABLE product_images RENAME COLUMN id_new TO id;
ALTER TABLE product_images ALTER COLUMN id SET NOT NULL;
ALTER TABLE product_images ADD CONSTRAINT product_images_pkey PRIMARY KEY (id);

ALTER TABLE product_images DROP COLUMN product_id;
ALTER TABLE product_images RENAME COLUMN product_id_new TO product_id;
ALTER TABLE product_images
    ADD CONSTRAINT product_images_product_fk FOREIGN KEY (product_id) REFERENCES products (id);

ALTER TABLE order_items DROP COLUMN product_id;
ALTER TABLE order_items RENAME COLUMN product_id_new TO product_id;
ALTER TABLE order_items
    ADD CONSTRAINT order_items_product_fk FOREIGN KEY (product_id) REFERENCES products (id);

-- 5) Identity: yangi qatorlar bazaning o'zida raqamlanadi (Hibernate IDENTITY strategiyasi).
--    Ketma-ketlik mavjud maksimal raqamdan davom etadi.
ALTER TABLE products       ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE product_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(pg_get_serial_sequence('products', 'id'),
              COALESCE((SELECT max(id) FROM products), 0) + 1, false);
SELECT setval(pg_get_serial_sequence('product_images', 'id'),
              COALESCE((SELECT max(id) FROM product_images), 0) + 1, false);
