--liquibase formatted sql

--changeset kitobgo:0019-product-categories
CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(100) NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX categories_name_lower_unique ON categories (lower(name));

CREATE TABLE product_categories (
    product_id bigint NOT NULL,
    category_id bigint NOT NULL,
    CONSTRAINT product_categories_pkey PRIMARY KEY (product_id, category_id),
    CONSTRAINT product_categories_product_fk FOREIGN KEY (product_id)
        REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT product_categories_category_fk FOREIGN KEY (category_id)
        REFERENCES categories (id)
);

CREATE INDEX product_categories_category_idx ON product_categories (category_id);

--rollback DROP TABLE product_categories;
--rollback DROP TABLE categories;
